// Generated by tools/release_identity.py sync; edit tools/release_identity.json.
#pragma once

#define RSDECK_VERSION_MAJOR 2
#define RSDECK_VERSION_MINOR 2
#define RSDECK_VERSION_PATCH 4
#define RSDECK_VERSION_STRING "2.2.4"

#ifndef RATSPEAK_BUILD_REVISION
#define RATSPEAK_BUILD_REVISION unknown
#endif
#ifndef RATSPEAK_BUILD_DIRTY
#define RATSPEAK_BUILD_DIRTY 1
#endif
#define RATSPEAK_STRINGIFY_IMPL(value) #value
#define RATSPEAK_STRINGIFY(value) RATSPEAK_STRINGIFY_IMPL(value)
#define RATSPEAK_COMPONENT_ID(board, role) "RATSPEAK-HANDHELD-COMPONENT:v1:" board ":" role ":" RSDECK_VERSION_STRING ":" RATSPEAK_STRINGIFY(RATSPEAK_BUILD_REVISION) ":" RATSPEAK_STRINGIFY(RATSPEAK_BUILD_DIRTY)

// Keep the identifier in linked images without serial output or storage writes.
inline void ratspeakRetainComponentId(const char* identity) {
    __asm__ __volatile__("" : : "r"(identity));
}
