#!/usr/bin/env python3
"""One product identity; generated firmware version and checked source consumers.

Normal firmware builds use the included header and archives. Only developer
graph/archive checks require Git and sibling Rust sources. The product manifest
contains no private harness dependencies. Each Lite repository owns its trusted
lineage; a handheld candidate must select commits consistent with that lineage.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

from release_catalog import BOARDS, ROOT


IDENTITY_PATH = Path("tools/release_identity.json")
HEADER_PATH = Path("src/core/config/FirmwareVersion.h")
RNODE_HEADER_PATH = Path("vendor/rnode_firmware/RatspeakBuildIdentity.h")
WORKFLOW_PATH = Path(".github/workflows/build.yml")
SOURCE_VARIABLES = {
    "rsReticulumLite": "RNS_LITE_COMMIT",
    "rsLXMFLite": "LXMF_LITE_COMMIT",
    "rsReticulum": "RNS_FULL_COMMIT",
    "rsLXMF": "LXMF_FULL_COMMIT",
    "rsLXST": "LXST_COMMIT",
}
SOURCE_ROLES = {name: "firmware" if name.endswith("Lite") or name == "rsLXST" else "trusted-validation"
                for name in SOURCE_VARIABLES}
SHA = re.compile(r"[0-9a-f]{40}")
SEMVER = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?")


def validate_version(version: str) -> re.Match:
    match = SEMVER.fullmatch(version)
    if not match or any(part.isdigit() and len(part) > 1 and part[0] == "0"
                        for part in (match[4] or "").split(".")):
        raise ValueError("invalid firmware version (expected SemVer without build metadata)")
    return match


def load_identity(root: Path = ROOT) -> dict:
    identity = json.loads((root / IDENTITY_PATH).read_text())
    if set(identity) != {"schema_version", "product", "version", "archive_toolchain", "sources"} or identity["schema_version"] != 1:
        raise ValueError("invalid release identity schema")
    if identity["product"] != "ratspeak-handheld":
        raise ValueError("unexpected release product")
    validate_version(identity["version"])
    if not re.fullmatch(r"rustc [^\r\n]+", identity["archive_toolchain"]):
        raise ValueError("invalid archive toolchain identity")
    if set(identity["sources"]) != set(SOURCE_ROLES):
        raise ValueError("release sources must contain exactly the firmware and trusted-validation graph")
    for name, source in identity["sources"].items():
        if (set(source) != {"commit", "role"} or not SHA.fullmatch(source["commit"])
                or source["role"] != SOURCE_ROLES[name]):
            raise ValueError(f"invalid pinned source or role: {name}")
    return identity


def source_pins(root: Path = ROOT, *, role: str | None = None) -> dict[str, str]:
    return {name: source["commit"] for name, source in load_identity(root)["sources"].items()
            if role is None or source["role"] == role}


def version_header(root: Path = ROOT) -> str:
    version = load_identity(root)["version"]
    match = validate_version(version)
    return ("// Generated by tools/release_identity.py sync; edit tools/release_identity.json.\n"
            "#pragma once\n\n"
            + "".join(f"#define RSDECK_VERSION_{part} {match[index]}\n"
                      for index, part in enumerate(("MAJOR", "MINOR", "PATCH"), 1))
            + f'#define RSDECK_VERSION_STRING "{version}"\n\n'
            + '#ifndef RATSPEAK_BUILD_REVISION\n#define RATSPEAK_BUILD_REVISION unknown\n#endif\n'
            + '#ifndef RATSPEAK_BUILD_DIRTY\n#define RATSPEAK_BUILD_DIRTY 1\n#endif\n'
            + '#define RATSPEAK_STRINGIFY_IMPL(value) #value\n'
            + '#define RATSPEAK_STRINGIFY(value) RATSPEAK_STRINGIFY_IMPL(value)\n'
            + '#define RATSPEAK_COMPONENT_ID(board, role) "RATSPEAK-HANDHELD-COMPONENT:v1:" board ":" role ":" RSDECK_VERSION_STRING ":" RATSPEAK_STRINGIFY(RATSPEAK_BUILD_REVISION) ":" RATSPEAK_STRINGIFY(RATSPEAK_BUILD_DIRTY)\n\n'
            + '// Keep the identifier in linked images without serial output or storage writes.\n'
            + 'inline void ratspeakRetainComponentId(const char* identity) {\n'
            + '    __asm__ __volatile__("" : : "r"(identity));\n'
            + '}\n')


def firmware_version(root: Path = ROOT, board: str | None = None) -> str:
    if (root / HEADER_PATH).read_text() != version_header(root):
        raise ValueError("generated firmware version is stale; run tools/release_identity.py sync")
    for name in ([board] if board else BOARDS):
        if name not in BOARDS:
            raise ValueError(f"unknown firmware board: {name}")
        config = (root / f"src/boards/{name}/config/BoardConfig.h").read_text()
        if '#include "config/FirmwareVersion.h"' not in config:
            raise ValueError(f"{name}: missing shared firmware version include")
        if re.search(r"^\s*#\s*(?:define|undef)\s+RSDECK_VERSION_", config, re.M):
            raise ValueError(f"{name}: duplicate firmware version definition")
    return load_identity(root)["version"]


def check_workflow_pins(text: str, variables: dict[str, str]) -> None:
    for variable, expected in variables.items():
        matches = re.findall(rf"^  {variable}: ([^\s#]+)", text, re.M)
        if matches != [expected]:
            raise ValueError(f"workflow differs from selected {variable} pin")
        if f"ref: ${{{{ env.{variable} }}}}" not in text:
            raise ValueError(f"workflow does not consume {variable}")


def check_local(root: Path = ROOT) -> None:
    firmware_version(root)
    if (root / RNODE_HEADER_PATH).read_text() != version_header(root):
        raise ValueError("generated RNode build identity is stale; run tools/release_identity.py sync")
    check_workflow_pins((root / WORKFLOW_PATH).read_text(),
                        {SOURCE_VARIABLES[name]: ref for name, ref in source_pins(root).items()})


def sync(root: Path = ROOT) -> None:
    """Generate local mirrors only; never invent pins or update sibling lineage."""
    for relative in (HEADER_PATH, RNODE_HEADER_PATH):
        header = root / relative
        header.parent.mkdir(parents=True, exist_ok=True)
        header.write_text(version_header(root))
    path = root / WORKFLOW_PATH
    text = path.read_text()
    for name, ref in source_pins(root).items():
        text, count = re.subn(rf"^  {SOURCE_VARIABLES[name]}: [^\n]+$",
                              f"  {SOURCE_VARIABLES[name]}: {ref}", text, flags=re.M)
        if count != 1:
            raise ValueError(f"missing or duplicate workflow pin: {name}")
    path.write_text(text)
    check_local(root)


def source_identity(root: Path) -> tuple[str, bool]:
    try:
        top = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], cwd=root, text=True, stderr=subprocess.DEVNULL
        ).strip()
        if Path(top).resolve() != root.resolve():
            raise ValueError("not the source repository root")
        revision = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
    except (subprocess.CalledProcessError, ValueError):
        # Source-release archives have no Git history. Let users build them, but
        # never label a local archive build as an unmodified official checkout.
        metadata = root.parent / "SOURCE.json"
        if not metadata.is_file():
            raise ValueError("source identity requires a Git checkout or the complete release source archive") from None
        revision = json.loads(metadata.read_text()).get("sources", {}).get(root.name, "")
        if not re.fullmatch(r"[0-9a-f]{40}", revision):
            raise ValueError("invalid source-archive identity")
        return revision, True
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("packaging requires a Git checkout with a full source commit")
    status = subprocess.check_output(
        ["git", "status", "--porcelain", "--untracked-files=all"], cwd=root, text=True
    )
    return revision, bool(status.strip())


def read_refs(text: str) -> dict[str, str]:
    refs = {}
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        fields = line.split()
        if len(fields) != 2 or fields[0] in refs or not SHA.fullmatch(fields[1]):
            raise ValueError("malformed or duplicate source lineage")
        refs[fields[0]] = fields[1]
    return refs


def check_lineage(root: Path = ROOT) -> None:
    pins = source_pins(root)
    expected = {
        ("rsReticulumLite", "TRUSTED_REF"): {"rsReticulum": pins["rsReticulum"]},
        ("rsLXMFLite", "TRUSTED_REF"): {name: pins[name] for name in ("rsReticulum", "rsLXMF")},
        ("rsLXMFLite", "RNS_LITE_REF"): {"rsReticulumLite": pins["rsReticulumLite"]},
    }
    for (repo, path), refs in expected.items():
        if read_refs((root.parent / repo / path).read_text()) != refs:
            raise ValueError(f"{repo}/{path}: lineage differs from selected source graph")
    mirrors = {
        "rsReticulumLite": {"RSLITE_RSRETICULUM_COMMIT": pins["rsReticulum"]},
        "rsLXMFLite": {
            "LXMFLITE_RSRETICULUMLITE_COMMIT": pins["rsReticulumLite"],
            "LXMFLITE_RSRETICULUM_COMMIT": pins["rsReticulum"],
            "LXMFLITE_RSLXMF_COMMIT": pins["rsLXMF"],
        },
    }
    for repo, variables in mirrors.items():
        for workflow in ("ci.yml", "release-readiness.yml"):
            check_workflow_pins((root.parent / repo / ".github/workflows" / workflow).read_text(), variables)


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=root, text=True).strip()


def check_workspace(root: Path = ROOT, *, allow_dirty: bool = False) -> None:
    check_local(root)
    if not allow_dirty and git(root, "status", "--porcelain", "--untracked-files=all"):
        raise ValueError("ratspeak-handheld: source checkout is dirty")
    for name, expected in source_pins(root).items():
        source = root.parent / name
        if Path(git(source, "rev-parse", "--show-toplevel")).resolve() != source.resolve():
            raise ValueError(f"{name}: not the source repository root")
        if git(source, "rev-parse", "HEAD") != expected:
            raise ValueError(f"{name}: source checkout must be at selected {expected}")
        if not allow_dirty and git(source, "status", "--porcelain", "--untracked-files=all"):
            raise ValueError(f"{name}: source checkout is dirty")
    check_lineage(root)


def archive_inputs(root: Path = ROOT) -> str:
    """Fingerprint actual Lite inputs as well as their selected commit identities."""
    from source_fingerprint import source_fingerprint

    records = {"identity": load_identity(root), "firmware_sources": {}}
    for name, expected in source_pins(root, role="firmware").items():
        source = root.parent / name
        actual = git(source, "rev-parse", "HEAD")
        if actual != expected:
            raise ValueError(f"{name}: archive input is not at selected {expected}")
        records["firmware_sources"][name] = {
            "commit": actual, "source_sha256": source_fingerprint(source),
            "dirty": bool(git(source, "status", "--porcelain", "--untracked-files=all")),
        }
    return hashlib.sha256(json.dumps(records, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "sync", "version", "toolchain", "sources", "check-lineage", "check-workspace", "archive-inputs", "build-flags"))
    parser.add_argument("--allow-dirty", action="store_true", help="development workspace only; exact selected HEADs still required")
    args = parser.parse_args()
    if args.allow_dirty and args.command != "check-workspace":
        parser.error("--allow-dirty is only valid with check-workspace")
    if args.command == "sync":
        sync()
    elif args.command == "build-flags":
        check_local()
        revision, dirty = source_identity(ROOT)
        print(f"-DRATSPEAK_BUILD_REVISION={revision} -DRATSPEAK_BUILD_DIRTY={int(dirty)}")
        return
    elif args.command == "version":
        print(firmware_version())
        return
    elif args.command == "toolchain":
        print(load_identity()["archive_toolchain"])
        return
    elif args.command == "sources":
        print(json.dumps(load_identity()["sources"], indent=2))
        return
    elif args.command == "archive-inputs":
        print(archive_inputs())
        return
    elif args.command == "check-workspace":
        check_workspace(allow_dirty=args.allow_dirty)
    elif args.command == "check-lineage":
        check_lineage()
    else:
        check_local()
    print(f"release identity: PASS ({load_identity()['version']}; {args.command})")


if __name__ == "__main__":
    main()
